kind: pipeline
name: default
steps:
- name: build
  image: gradle:4.5.1-jdk9
  commands: 
  - gradle --help -- --coverage
- name: docker
  image: plugins/docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dodev123/try
    tags: latest
- name: kubectl
  image: quay.io/honestbee/drone-kubernetes
  secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
  commands:
  - kubectl get pods
  
