kind: pipeline
name: default
steps:
- name: build
  image: gradle:4.5.1-jdk9
  commands: 
  - gradle --help
- name: docker
  image: plugins/docker
  secrets: [ docker_username, docker_password ]
  repo: komljen/test-image
  tags: ${DRONE_COMMIT_SHA}
- name: kubectl
  image: komljen/drone-kubectl-helm
  secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
  kubectl: "get pods"
